### ISSUE TITLE
Warning: Execution of event hook

### ISSUE THREAD

**Issue by DevMinkh** [IamLation/lation_pawnshop#10]
I have created some shops and now if someone sell any item i got x rows like

`[script:ox_inventory:] Warning: Execution of event hook "lation_pawnshop:swapItems:6" took 1678.64ms.`

Is this a known problem?

LG

**Comment by IamLation** [comment]
Hey! This is completely normal & expected behavior. We are using the inventory hook in a way that is probably not intended and we are stalling the execution of that hook when we display the dialog to confirm the transaction. So that warning that tells you the execution of the hook took Xms is just the duration it took for someone to hit confirm or whatever on the confirmation box. Hooks aren't meant to be stalled in the way we do so in the script, so it's to be expected. It's just a warning, not an error. Hope this helps.

**Comment by DevMinkh** [comment]
Ty for the information this can be closed
